[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    content-type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    content-type = "application/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    content-type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    content-type = "text/css"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    content-type = "application/json"
