[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "./backend"

[services.environment]
PORT = "8080"

[[services]]
name = "frontend"
source = "./frontend"

[services.environment]
VITE_API_URL = "https://your-backend-service.railway.app"
